### ISSUE TITLE
cgo/daxpy crashes when n == 0

### ISSUE THREAD

**Issue by btracey** [gonum/blas#138]
If n == 0, daxpy should just return, not crash with a non-zero increment. I assume this is a problem in more than just Daxpy. I have a test for this (created to fix #137).

**Comment by kortschak** [comment]
I don't think this is true. The inc must be >= 1 irrespective of the value of n.

**Comment by kortschak** [comment]
I can't see the test.

A survey of the fortran shows that they also return when n < 0 or incX == 0 for dasum (we panic in those cases). The issue is whether we follow the behaviour of netlib 100% or not - we currently don't. Arguably, our behaviour is better; inc == 0 is not valid for any case (unless we make the exception for n == 0). If we make the special case for n == 0, then an incorrectly built call does not fail until an, e.g. blas64, value is passed with n != 0. I would prefer the failure to happen the first time an invalid inc is used.

This means that the zero values for the blas64 etc types are not valid - I'm OK with that.

**Comment by btracey** [comment]
SGTM
